{{- if .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "pcp.frontend.fullname" . }}
  labels:
    {{- include "pcp.labels" . | nindent 4 }}
    {{- include "pcp.frontend.selectorLabels" . | nindent 4 }}
spec:
  {{- if .Values.frontend.route.host }}
  host: {{ .Values.frontend.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "pcp.frontend.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
