apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pcp.fullname" . }}
  labels:
    {{- include "pcp.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "pcp.databaseUrl" . | b64enc | quote }}
  auth-token: {{ .Values.backend.authToken | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
